framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
             queue: '%env(MESSENGER_TRANSPORT_DSN)%'
             queue2: '%env(MESSENGER_TRANSPORT_DSN2)%'
        routing:
            # Route your messages to the transports
             'Shared\TestMessage': [queue, queue2]